WOADD-564 : Indication for resit
lee-acn/andfmoodle pull request #149
Opened 2021-01-08 19:19 UTC by natividadelijah

*** PLEASE DO NOT OPEN PULL REQUESTS VIA GITHUB ***

The moodle.git repository at Github is just a mirror of the official repository. We do not accept pull requests at Github.

See CONTRIBUTING.txt guidelines for how to contribute patches for Moodle. Thank you.

--

2021-01-09 08:12 UTC, m-aquino requested changes

2021-01-09 08:12 UTC, m-aquino commented on local/gugcat/classes/grade_aggregation.php
> +        }
`$grade_->information = is_null($grade_->information) ? null : '1';`
One liner check would suffice.

2021-01-09 08:12 UTC, m-aquino commented on local/gugcat/classes/grade_aggregation.php
> +        $grade_->usermodified = $studentno;
The usermodified is the the userid of the person who modified this grade, if so the current user.

2021-01-09 08:12 UTC, m-aquino commented on local/gugcat/overview/index.php
> +        $status = grade_aggregation::require_resit($studentno);
No need to assign it to another variable if it will not be used.

2021-01-11 04:05 UTC, m-aquino approved these changes

2021-01-11 04:09 UTC, uofg-andf approved these changes

2021-01-11 04:09 UTC, uofg-andf commented on local/gugcat/overview/index.php
> +        header("Location: ".$_SERVER['REQUEST_URI']);
Please try using redirect($url).

2021-01-11 04:09 UTC, merged