Added unit test
lee-acn/andfmoodle pull request #162
Opened 2021-01-12 04:16 UTC by deguzman22

*** PLEASE DO NOT OPEN PULL REQUESTS VIA GITHUB ***

The moodle.git repository at Github is just a mirror of the official repository. We do not accept pull requests at Github.

See CONTRIBUTING.txt guidelines for how to contribute patches for Moodle. Thank you.

--

2021-01-12 06:42 UTC, natividadelijah approved these changes

2021-01-12 06:53 UTC, m-aquino requested changes

2021-01-12 06:53 UTC, m-aquino commented on local/gugcat/tests/gugcat_test.php
> +        $this->assertNotNull($gradeitems, "");
$this->assertNotNull($gradeversions, ""); 
Assert not null is not enough for the test. There should be an expected result then assert equal or contains.

2021-01-13 05:55 UTC, uofg-andf approved these changes

2021-01-13 07:24 UTC, natividadelijah approved these changes

2021-01-13 07:39 UTC, m-aquino approved these changes

2021-01-13 07:39 UTC, merged