fix for release provisional error
lee-acn/andfmoodle pull request #308
Opened 2021-02-02 11:27 UTC by natividadelijah

*** PLEASE DO NOT OPEN PULL REQUESTS VIA GITHUB ***

The moodle.git repository at Github is just a mirror of the official repository. We do not accept pull requests at Github.

See CONTRIBUTING.txt guidelines for how to contribute patches for Moodle. Thank you.

--

2021-02-02 11:44 UTC, m-aquino requested changes

2021-02-02 11:44 UTC, m-aquino commented on local/gugcat/classes/grade_capture.php
> +                        if($item->grades[$student->id]->hidden == 1)
just use && operator

2021-02-03 03:03 UTC, m-aquino approved these changes

2021-02-03 10:46 UTC, uofg-andf approved these changes

2021-02-03 10:46 UTC, merged