Added comments
lee-acn/andfmoodle pull request #311
Opened 2021-02-03 02:38 UTC by deguzman22

*** PLEASE DO NOT OPEN PULL REQUESTS VIA GITHUB ***

The moodle.git repository at Github is just a mirror of the official repository. We do not accept pull requests at Github.

See CONTRIBUTING.txt guidelines for how to contribute patches for Moodle. Thank you.

--

2021-02-03 03:38 UTC, m-aquino requested changes
Please make the comments precise.

2021-02-03 03:38 UTC, m-aquino commented on local/gugcat/locallib.php
> +     * Returns value of intvalue
Which intvalue? please add more description for this function

2021-02-04 04:13 UTC, m-aquino approved these changes

2021-02-04 04:17 UTC, natividadelijah approved these changes

2021-02-04 06:00 UTC, uofg-andf approved these changes

2021-02-04 06:00 UTC, lee-acn commented on local/gugcat/locallib.php
> +     *  Custom field method to create and update value of customfield_data
Please check alignment of comments.

2021-02-04 06:00 UTC, merged