Import non-22pt scale grades (bulk import)
lee-acn/andfmoodle pull request #475
Opened 2021-04-06 11:47 UTC by JMAbreu-acn

*** PLEASE DO NOT OPEN PULL REQUESTS VIA GITHUB ***

The moodle.git repository at Github is just a mirror of the official repository. We do not accept pull requests at Github.

See CONTRIBUTING.txt guidelines for how to contribute patches for Moodle. Thank you.

--

2021-04-06 13:40 UTC, uofg-andf requested changes

2021-04-06 13:40 UTC, uofg-andf commented on local/gugcat/index.php
> +        $grademin = $selectedmodule->gradeitem->grademin;
I think we need to check the $activity and not the $selectedmodule for $grademin.

2021-04-06 13:40 UTC, uofg-andf commented on local/gugcat/index.php
> +            (!$valid_import_activity)){
Can (!$valid_import_activity) cover all of the conditions?

2021-04-07 05:29 UTC, uofg-andf approved these changes

2021-04-07 05:30 UTC, m-aquino approved these changes

2021-04-07 06:30 UTC, natividadelijah approved these changes

2021-04-07 06:30 UTC, merged